### ISSUE TITLE
[STORY] Deploy T1-weighted pipeline as XNAT "app"

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#251]
### Metadata

Epic: #17 
Feature: #238 
Feature Release:
Required knowledge: mid-level

### Description

We need to be able to deploy pipeline build in #230 as XNAT "app" using deployment pipeline

### Acceptance Criteria

- [x] 1. Be able to run pipeline as XNAT pipeline
- [ ] 2. Users should be able to select their parcellation file (ideally multiple different parcellations)
- [ ] 3. Users should be able to access FS output files (potentially option to keep the fastsurfer output or not)

### Blocked by

- [ ] 

```[tasklist]
### Tasks
- [ ] tidy up outputs directory (remove tmp folders, keep/move FS directory after final Parc is generated)
- [ ] create some sort of subject identifier (maybe this is automatically done?)
```

**Comment by tclose** [comment]
Completed in #488
