### ISSUE TITLE
[EPIC] Automated quality assurance workflows

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#35]
### Hypothesis Statement
- Funnel Entry Date: 15/6/22
- Epic Name:  Integrated quality assurance workflows
- Epic Owner: @tclose 

### Description

For users of AIS-linked/NIF facilities who acquire imaging data, *Automated quality assurance workflows* are a suite of pipelines integrated into AIS-XNAT that ensure the quality of imaging data and the instruments that acquired them. Unlike ad-hoc quality control measures, automated quality assurance workflows are run regularly to pick up any deviations from expected performance.

### Outcomes

- Improve quality of scientific research across the network
- Attract more users to the service

### Leading Indicators

- Number of sites that are subscribed to the service

### Nonfunctional Requirements

- Regularity of quality assurance

```[tasklist]
### Features
- [ ] https://github.com/Australian-Imaging-Service/pipelines/issues/55
- [ ] https://github.com/Australian-Imaging-Service/pipelines/issues/65
- [ ] https://github.com/Australian-Imaging-Service/pipelines/issues/66
- [ ] https://github.com/Australian-Imaging-Service/pipelines/issues/65
