### ISSUE TITLE
[FEATURE] Polishing of Arcana package ahead of major release

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#44]
### Description
Comprehensive unit tests covering Arcana package

### Benefit Hypothesis

If there are comprehensive unit tests for Arcana, then changes to the package are much less likely to introduce unnoticed bugs.

### Acceptance Criteria

 - [ ] Behaviour exactly matches [docs](https://arcana.readthedocs.io/en/latest)

### Stories

- [ ] Australian-Imaging-Service/arcana#56
- [ ] Australian-Imaging-Service/arcana#47
- [ ] Australian-Imaging-Service/arcana#16
- [ ] Australian-Imaging-Service/arcana#13
- [x] Australian-Imaging-Service/arcana#110
- [x] Australian-Imaging-Service/arcana#96
- [x] Australian-Imaging-Service/arcana#97
- [ ] Australian-Imaging-Service/arcana#100
- [ ] #113
- [ ] Australian-Imaging-Service/arcana#122
